### ISSUE TITLE
critical error on clean install of grav with composer

### ISSUE THREAD

**Issue by rvantonisse** [getgrav/grav-plugin-problems#22]
Clean install of Grav with composer gives me:

```
[2018-12-16 17:05:48] grav.CRITICAL: Call to a member function check() on null
  Trace:
    #0 ./user/plugins/problems/problems.php(33): Grav\Plugin\ProblemsPlugin->problemsFound()
    #1 ./vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\ProblemsPlugin->onFatalException(Object(RocketTheme\Toolbox\Event\Event), 'onFatalExceptio...', Object(RocketTheme\Toolbox\Event\EventDispatcher))
    #2 ./vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onFatalExceptio...', Object(RocketTheme\Toolbox\Event\Event))
    #3 ./vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onFatalExceptio...', Object(RocketTheme\Toolbox\Event\Event))
    #4 ./system/src/Grav/Common/Grav.php(279): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onFatalExceptio...', Object(RocketTheme\Toolbox\Event\Event))
    #5 ./index.php(56): Grav\Common\Grav->fireEvent('onFatalExceptio...', Object(RocketTheme\Toolbox\Event\Event))
    #6 {main} [] []

```
On homebrewed mac os mojave
Grav Package Manager 1.5.6
Composer version 1.8.0 2018-12-03 10:31:16
PHP 7.3.0 (cli) (built: Dec  7 2018 11:00:11) ( NTS )

Running php -S localhost:8000 system/router.php

Uninstalling problems-plugin make the initial grav site work.
Rolling back to Grav 1.5.5 does not help

Need other debug info? please let me know.

**Comment by rhukster** [comment]
There was an issue in Problems v2.0.1 that caused this error if a fatal exception was thrown.  I've fixed this and released v2.0.2.

However, the bigger issue is the fatal error in the first place.  I think this stems from PHP 7.3.0 (which is brand new) and is causing some issues in the RocketTheme/Toolbox library we use to handle the Configuration.  Currently, Grav is not compatible with PHP 7.3 until this issue is resolved.
